### ISSUE TITLE
Cambios de Excel de USA

### ISSUE THREAD

**Issue by USUARIOSTI** [Super-Transporte-Internacional/REPEQ#2]
Cuando el estatus del remolque es TRANSITO, CARGNADO o DESCARGANDO, que la POSICION sea el DESTINATARIO.

**Comment by USUARIOSTI** [comment]
este es un comentario

**Comment by Mexpredator** [comment]
Se realizaron los cambios al procedimiento almacenador para poder agarrar la posicion del destinatario si el remolque se encuentra en TRANSITO, CARGNADO o DESCARGANDO
