### ISSUE TITLE
Respetar posicion

### ISSUE THREAD

**Issue by USUARIOSTI** [Super-Transporte-Internacional/REPEQ#3]
Cuando finaliza un viaje el remolque que respeta la ultima posición del remolque osea el ultimo destinatario.

**Comment by Mexpredator** [comment]
Se trabaja para realizar cambio en donde busque el ultimo pedido realizado, y que obtenga la posición del DESTINO si la fecha de fecha_real_fin_viaje es mas actual que la fecha de la posición del equipo en REPEQ

**Comment by Mexpredator** [comment]
se realizaron los cambios, en donde obtiene la plaza destino del ultimo pedido cerrado si es que no tiene un pedido en transito, se subio esta actualizacion al REPEQ de produccion, se verifica primero antes de cerrar la peticion

**Comment by Mexpredator** [comment]
Cerrado
